[project]
name = "openwebui-developer-toolkit"
version = "0.1.0"
description = "Self-contained Pipes, Filters & Tools for Open WebUI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "httpx",
  "fastapi",
  "pydantic"
]

[project.optional-dependencies]
dev = [
  "requests",
  "ruff",
  "pytest"
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = [
  "external*",
  "tests*"
]

[tool.pytest.ini_options]
# Only collect tests from our local ``tests`` directory
testpaths = ["tests"]
addopts = "-ra"
