name: Weekly OpenWebUI sync

on:
  schedule:
    - cron: "0 7 * * 1"  # every Monday at 07:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update external copy
        run: |
          set -euo pipefail
          rm -rf external/open-webui
          git clone --depth 1 https://github.com/open-webui/open-webui.git external/open-webui
          rm -rf external/open-webui/.git

      - name: Commit & push changes
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          set -euo pipefail

          git add -f external/open-webui
          if git diff --cached --quiet ; then
            echo "No updates – nothing to commit."
            exit 0
          fi

          git commit -m "chore: weekly OpenWebUI snapshot (auto-sync)"
          git push origin HEAD
