name: OpenWebUI Extension Deployment

on:
  push:
    branches: [ dev, main ]
    paths:
      - 'functions/**.py'
      - 'tools/**.py'
      - '.scripts/publish_to_webui.py'
  workflow_dispatch:

jobs:
# ───────────────────────────────────────────
# Deploy to GLC when committing to dev
# ───────────────────────────────────────────
  deploy-glc:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: staging-glc

    steps:
      - uses: actions/checkout@v4          # pull two commits so diff works
        with: { fetch-depth: 2 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      # ➊ get list of changed plugin files (works for merges)
      - name: Get changed plugin files
        id: changed
        uses: tj-actions/changed-files@v43
        with:
          files: |
            functions/pipes/**/*.py
            functions/filters/**/*.py
            tools/**/*.py

      # ➋ publish each changed file
      - name: Publish to GLC
        if: steps.changed.outputs.any_changed == 'true'
        env:
          WEBUI_URL: ${{ vars.WEBUI_URL }}
          WEBUI_KEY: ${{ secrets.WEBUI_KEY }}
        run: |
          IFS=$'\n'
          for file in ${{ steps.changed.outputs.all_changed_files }}; do
            echo "Publishing $file to GLC …"
            if [[ "$file" == functions/pipes/* ]]; then
              type=pipe
            elif [[ "$file" == functions/filters/* ]]; then
              type=filter
            elif [[ "$file" == tools/* ]]; then
              type=tool
            else
              type=pipe
            fi
            python .scripts/publish_to_webui.py "$file" --type "$type"
          done
          unset IFS

# ───────────────────────────────────────────
# Deploy to CLAC when committing to main
# ───────────────────────────────────────────
  deploy-clac:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production-clac

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Get changed plugin files
        id: changed
        uses: tj-actions/changed-files@v43
        with:
          files: |
            functions/pipes/**/*.py
            functions/filters/**/*.py
            tools/**/*.py

      - name: Publish to CLAC
        if: steps.changed.outputs.any_changed == 'true'
        env:
          WEBUI_URL: ${{ vars.WEBUI_URL }}
          WEBUI_KEY: ${{ secrets.WEBUI_KEY }}
        run: |
          IFS=$'\n'
          for file in ${{ steps.changed.outputs.all_changed_files }}; do
            echo "Publishing $file to CLAC …"
            if [[ "$file" == functions/pipes/* ]]; then
              type=pipe
            elif [[ "$file" == functions/filters/* ]]; then
              type=filter
            elif [[ "$file" == tools/* ]]; then
              type=tool
            else
              type=pipe
            fi
            python .scripts/publish_to_webui.py "$file" --type "$type"
          done
          unset IFS
