name: Deploy OpenWebUI Extensions

on:
  push:
    branches: [ main ]                            # 🚀 only main auto-deploys
    paths:
      - 'src/openwebui_devtoolkit/**.py'          # run only if a plugin changed
      - 'scripts/publish_to_webui.py'

# ─────────────────────────────────────────────────────────────────────
# 1.  STAGING  (GLC)  — automatic
# ─────────────────────────────────────────────────────────────────────
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging-glc                      # uses staging-glc secrets

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests python-dotenv

      # ← list all changed plugin files (works for merge commits too)
      - name: Get changed plugin files
        id: changed
        uses: tj-actions/changed-files@v43
        with:
          files: |
            src/openwebui_devtoolkit/pipes/**/*.py
            src/openwebui_devtoolkit/filters/**/*.py
            src/openwebui_devtoolkit/tools/**/*.py

      - name: Publish to GLC
        if: steps.changed.outputs.any_changed == 'true'
        env:
          WEBUI_URL: ${{ secrets.WEBUI_URL }}
          WEBUI_KEY: ${{ secrets.WEBUI_KEY }}
        run: |
          for file in ${{ steps.changed.outputs.changed_files }}; do
            echo "Publishing $file to GLC …"
            python scripts/publish_to_webui.py "$file"
          done

# ─────────────────────────────────────────────────────────────────────
# 2.  PRODUCTION  (CLAC)  — manual approval gate
# ─────────────────────────────────────────────────────────────────────
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:                                   # ⏸ waits for approval
      name: production-clac
      url:  https://ai.clac.ca

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install requests python-dotenv

      - name: Get changed plugin files
        id: changed
        uses: tj-actions/changed-files@v43
        with:
          files: |
            src/openwebui_devtoolkit/pipes/**/*.py
            src/openwebui_devtoolkit/filters/**/*.py
            src/openwebui_devtoolkit/tools/**/*.py

      - name: Publish to CLAC
        if: steps.changed.outputs.any_changed == 'true'
        env:
          WEBUI_URL: ${{ secrets.WEBUI_URL }}
          WEBUI_KEY: ${{ secrets.WEBUI_KEY }}
        run: |
          for file in ${{ steps.changed.outputs.changed_files }}; do
            echo "Publishing $file to CLAC …"
            python scripts/publish_to_webui.py "$file"
          done
