name: Deploy OpenWebUI Extensions

on:
  push:
    branches: [ main ]                     # 🚀 only main auto-deploys
    paths:
      - 'src/openwebui_devtoolkit/**.py'   # run only if a plugin changed
      - 'scripts/publish_to_webui.py'

jobs:
  # ------------------------------------------------------------------
  # 1.  STAGING  ─────────────────────────────────────────────────────
  # ------------------------------------------------------------------
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging-glc              # uses staging-glc secrets
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - run: pip install requests python-dotenv

      - name: Publish changed plugins to GLC
        env:
          WEBUI_URL: ${{ secrets.WEBUI_URL }}
          WEBUI_KEY: ${{ secrets.WEBUI_KEY }}
        run: |
          # list files changed in THIS commit (handles merge commits too)
          CHANGED=$(git diff-tree -m --no-commit-id --name-only -r "$GITHUB_SHA" | \
            grep -E '^src/openwebui_devtoolkit/(pipes|filters|tools)/.*\.py$' || true)

          if [ -z "$CHANGED" ]; then
            echo "No plugin files changed."
            exit 0
          fi

          for file in $CHANGED; do
            echo "Publishing $file …"
            python scripts/publish_to_webui.py "$file"
          done

  # ------------------------------------------------------------------
  # 2.  PRODUCTION (manual gate)  ─────────────────────────────────────
  # ------------------------------------------------------------------
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:                          # ⏸ waits for approval
      name: production-clac
      url: https://ai.clac.ca             # shows in the UI
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - run: pip install requests python-dotenv

      - name: Publish to CLAC
        env:
          WEBUI_URL: ${{ secrets.WEBUI_URL }}
          WEBUI_KEY: ${{ secrets.WEBUI_KEY }}
        run: |
          CHANGED=$(git diff-tree -m --no-commit-id --name-only -r "$GITHUB_SHA" | \
            grep -E '^src/openwebui_devtoolkit/(pipes|filters|tools)/.*\.py$' || true)

          if [ -z "$CHANGED" ]; then
            echo "No plugin files changed."
            exit 0
          fi

          for file in $CHANGED; do
            echo "Publishing $file …"
            python scripts/publish_to_webui.py "$file"
          done
