name: Deploy OpenWebUI Extensions

on:
  push:
    branches: [ main ]                      # 🚀 deploy pipeline only on main
    paths:
      - 'src/openwebui_devtoolkit/**.py'    # run when a plugin changes
      - 'scripts/publish_to_webui.py'

jobs:
# ───────────────────────────────────────────
# 1.  STAGING  — GLC (auto)
# ───────────────────────────────────────────
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging-glc               # needs WEBUI_URL + WEBUI_KEY secrets

    steps:
      - uses: actions/checkout@v4          # pull two commits so diff works
        with: { fetch-depth: 2 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      # ➊ get list of changed plugin files (works for merges)
      - name: Get changed plugin files
        id: changed
        uses: tj-actions/changed-files@v43
        with:
          files: |
            src/openwebui_devtoolkit/pipes/**/*.py
            src/openwebui_devtoolkit/filters/**/*.py
            src/openwebui_devtoolkit/tools/**/*.py

      # ➋ publish each changed file
      - name: Publish to GLC
        if: steps.changed.outputs.any_changed == 'true'
        env:
          WEBUI_URL: ${{ secrets.WEBUI_URL }}
          WEBUI_KEY: ${{ secrets.WEBUI_KEY }}
        run: |
          for file in ${{ steps.changed.outputs.changed_files }}; do
            echo "Publishing $file to GLC …"
            python scripts/publish_to_webui.py "$file" --type pipe
          done

# ───────────────────────────────────────────
# 2.  PRODUCTION — CLAC (manual gate)
# ───────────────────────────────────────────
  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:                           # waits for *Approve & deploy*
      name: production-clac               # add yourself as required reviewer
      url:  https://ai.clac.ca

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 2 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Get changed plugin files
        id: changed
        uses: tj-actions/changed-files@v43
        with:
          files: |
            src/openwebui_devtoolkit/pipes/**/*.py
            src/openwebui_devtoolkit/filters/**/*.py
            src/openwebui_devtoolkit/tools/**/*.py

      - name: Publish to CLAC
        if: steps.changed.outputs.any_changed == 'true'
        env:
          WEBUI_URL: ${{ secrets.WEBUI_URL }}
          WEBUI_KEY: ${{ secrets.WEBUI_KEY }}
        run: |
          for file in ${{ steps.changed.outputs.changed_files }}; do
            echo "Publishing $file to CLAC …"
            python scripts/publish_to_webui.py "$file" --type pipe
          done
