name: Update Open WebUI

on:
  schedule: [{ cron: '0 7 * * 1' }]   # every Monday 07:00 UTC
  workflow_dispatch:

permissions:            # job may push & open PRs
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    # 1 ▸ checkout your repo
    - uses: actions/checkout@v4

    # 2 ▸ copy a fresh snapshot of OpenWebUI
    - name: Copy upstream OpenWebUI
      run: |
        rm -rf open-webui
        git clone --depth 1 https://github.com/open-webui/open-webui.git open-webui
        rm -rf open-webui/.git        # keep only the files

    # 3 ▸ commit & push only when something really changed
    - name: Commit (if needed)
      id: push
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git checkout -B update-open-webui

        if git diff --quiet; then          # nothing changed
          echo "changed=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        git add open-webui
        git commit -m "chore: update OpenWebUI snapshot"
        git push -u origin update-open-webui
        echo "changed=true" >> "$GITHUB_OUTPUT"

    # 4 ▸ create / update the PR only when we really have changes
    - name: Create or update PR
      if: steps.push.outputs.changed == 'true'
      env:
        GH_TOKEN: ${{ github.token }}
        BASE_BRANCH: ${{ github.event.repository.default_branch }}
      run: |
        # GitHub CLI is pre-installed on the runner 
        if gh pr view update-open-webui >/dev/null 2>&1; then
          gh pr edit update-open-webui \
             --title "chore: update OpenWebUI snapshot" \
             --body  "Automated weekly sync of the OpenWebUI code."
        else
          gh pr create \
             --title "chore: update OpenWebUI snapshot" \
             --body  "Automated weekly sync of the OpenWebUI code." \
             --head  update-open-webui \
             --base  "$BASE_BRANCH"
        fi
