# .github/workflows/update-open-webui.yml
name: Update Open WebUI

on:
  schedule: [{ cron: "0 7 * * 1" }]   # every Monday 07:00 UTC
  workflow_dispatch:

permissions:            # short-lived GITHUB_TOKEN can push & manage PRs
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ your repo
    - uses: actions/checkout@v4

    # 2 ▸ snapshot upstream
    - name: Clone upstream OpenWebUI
      run: |
        set -euo pipefail
        rm -rf external/open-webui
        git clone --depth 1 https://github.com/open-webui/open-webui.git external/open-webui
        rm -rf external/open-webui/.git   # remove the .git directory for clarity

    # 3 ▸ commit & push if anything changed
    - name: Commit & push branch
      id: push
      run: |
        set -euo pipefail
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git checkout -B update-open-webui
        git add -A

        if git diff --cached --quiet; then
          echo "changed=false" >>"$GITHUB_OUTPUT"
          exit 0
        fi

        git commit -m "chore: update OpenWebUI snapshot"
        git push -u origin update-open-webui
        echo "changed=true"  >>"$GITHUB_OUTPUT"

    # 4 ▸ open / update PR
    - name: Create or update PR
      if: steps.push.outputs.changed == 'true'
      env:
        GH_TOKEN: ${{ github.token }}
        BASE_BRANCH: ${{ github.event.repository.default_branch }}
      run: |
        set -euo pipefail
        if gh pr view update-open-webui >/dev/null 2>&1; then
          gh pr edit update-open-webui \
            --title "chore: update OpenWebUI snapshot" \
            --body  "Automated weekly sync of the OpenWebUI code."
        else
          gh pr create \
            --title "chore: update OpenWebUI snapshot" \
            --body  "Automated weekly sync of the OpenWebUI code." \
            --head  update-open-webui \
            --base  "$BASE_BRANCH"
        fi

    # 5 ▸ approve PR (satisfies simple “1 approval” rules)
    - name: Approve PR
      if: steps.push.outputs.changed == 'true'
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh pr review update-open-webui --approve -b "Automated approval"

    # 6 ▸ merge and delete branch
    - name: Merge & delete branch
      if: steps.push.outputs.changed == 'true'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        # Try immediate merge with admin bypass;
        # if that fails (e.g. pending checks), enable auto-merge instead.
        gh pr merge update-open-webui --merge --delete-branch --admin -y \
        || gh pr merge update-open-webui --merge --auto --delete-branch -y  [oai_citation:2‡GitHub CLI](https://cli.github.com/manual/gh_pr_merge?utm_source=chatgpt.com)
