name: Update Open WebUI

on:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Clone upstream repository
        run: |
          rm -rf open-webui
          git clone --depth 1 https://github.com/open-webui/open-webui.git open-webui
          rm -rf open-webui/.git
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: update open-webui'
          title: 'chore: update open-webui'
          body: Automated update of the open-webui folder.
          branch: update-open-webui
