# .github/workflows/update-open-webui.yml
# Sync the public OpenWebUI project into ./open-webui each Monday
# and open / refresh a pull-request with the changes.
# – No third-party actions except the official actions/checkout –
# – Uses only the short-lived GITHUB_TOKEN –

name: Update Open WebUI

on:
  schedule: [{ cron: "0 7 * * 1" }]   # every Monday 07:00 UTC ≈ 00:00 PT
  workflow_dispatch:                  # allow manual runs

# Grant this job just enough power to push & open PRs in this repo
permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # 1 ▸ check out YOUR repository
    - name: Check out code
      uses: actions/checkout@v4

    # 2 ▸ copy a fresh snapshot of OpenWebUI into ./open-webui
    - name: Copy upstream OpenWebUI
      run: |
        set -euo pipefail
        rm -rf open-webui
        git clone --depth 1 https://github.com/open-webui/open-webui.git open-webui
        rm -rf open-webui/.git        # drop the upstream .git dir

    # 3 ▸ commit & push only if something actually changed
    - name: Commit and push branch
      id: push
      run: |
        set -euo pipefail
        git config user.name  "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git checkout -B update-open-webui

        git add -A                                # stage new/changed/deleted files

        if git diff --cached --quiet; then        # nothing staged ⇒ nothing to do
          echo "changed=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        git commit -m "chore: update OpenWebUI snapshot"
        git push -u origin update-open-webui
        echo "changed=true" >> "$GITHUB_OUTPUT"

    # 4 ▸ open or update the pull-request only when we have a new commit
    - name: Create or update PR
      if: steps.push.outputs.changed == 'true'
      env:
        GH_TOKEN: ${{ github.token }}                            # give gh CLI auth
        BASE_BRANCH: ${{ github.event.repository.default_branch }} # main / master / …
      run: |
        set -euo pipefail
        # GitHub CLI is pre-installed on GitHub-hosted runners
        if gh pr view update-open-webui >/dev/null 2>&1; then
          gh pr edit update-open-webui \
            --title "chore: update OpenWebUI snapshot" \
            --body  "Automated weekly sync of the OpenWebUI code."
        else
          gh pr create \
            --title "chore: update OpenWebUI snapshot" \
            --body  "Automated weekly sync of the OpenWebUI code." \
            --head  update-open-webui \
            --base  "$BASE_BRANCH"
        fi
